sonar.projectKey=cake-shop
sonar.projectName=Cake Shop
sonar.sources=backend
sonar.tests=backend/cakehome/tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.exclusions=**/migrations/**,**/staticfiles/**
sonar.coverage.exclusions=**/tests/**,**/settings.py,**/wsgi.py,**/asgi.py,**/manage.py,**/migrations/**