sonar.projectKey=cake-shop
sonar.projectName=Cake Shop
sonar.sources=cakehome,config
sonar.tests=cakehome/tests
sonar.exclusions=**/migrations/**,**/staticfiles/**,**/tests/**
sonar.python.version=3.13
sonar.python.coverage.reportPaths=../reports/coverage.xml